### ISSUE TITLE
Switch case branches are incorrectly marked as reached on fallthrough.

### ISSUE THREAD

**Issue by jfmengels** [istanbuljs-archived-repos/istanbul-lib-instrument#31]
Hi there!

Two things first:
- Thanks a lot for this awesome tool and istanbul/nyc in general :heart: 
- I'm not sure I'm on the right repo, though this one looks to me like the most fitting one related to this problem. Let me know if I should move this issue somewhere else

I have discovered a problem with a false positive in code coverage reports, when dealing with switch cases and fallthroughs.

I have created a repo demonstrating the problem and some additional explanations in the README https://github.com/jfmengels/incorrect-coverage. I hope that that is sufficient explanation, but let me know if you wish for me to provide more.

(cc @ericelliott)

**Comment by ericelliott** [comment]
The coverage report is correct. It's not testing for which cases are engaged by the switch. Instead it's checking whether or not all of the code branches are covered by your tests. Thus, `case 2` is covered by the test for `case 1`, since the `case 1` branch falls through `case 2`.

**Comment by jfmengels** [comment]
I disagree. Case 1 & 2 and case 3 & 4 are actually similar, but for the first group, I pass through the first case and fall through the second, while for the second, I go directly to the fourth without going through the third. Same thing, but cases are just ordered differently, and the coverage result differs.

In this case, case 3 does get reported as not covered, which is correct, as it isn't, and case 2 should have had the same treatment.

**Comment by ericelliott** [comment]
> In this case, case 3 does get reported as not covered, which is correct, as it isn't, and case 2 should have had the same treatment.

Case 2 is reported as covered because the code for case 2 was exercised, which is what code coverage measures. The question is not "did I directly call this thing?" The question is "did this code run?"

That's the definition of code coverage. Whether you agree with that behavior or not is a moot point. The tool is working as intended, and to change it would mean redefining what coverage means for all the users of the tool -- which would be awkward, wouldn't it?

**Comment by jfmengels** [comment]
I think I see your point. Let me re-say that, just to make sure we're on the same page here. You say that since the code, or the "label", for `case 2` is run at some point in the progress of the evaluation of a switch case fallthrough. I agree that that is the definition for code coverage, for statements at least. But the branch coverage is something different I think.

I find it very odd and almost absurd that you would (and you currently do) get different branch coverage results depending on if you do:

```js
switch (x) {
	case 1:
	case 2:
		return 'ok';
}
// or
switch (x) {
	case 2:
	case 1:
		return 'ok';
}
```

> The tool is working as intended, and to change it would mean redefining what coverage means for all the users of the tool -- which would be awkward, wouldn't it?

(Would be interesting to know how everybody defines code coverage, and 100% code coverage by the way)
It might make it a bit awkward, but as long as it makes the tool more useful, why not? When people care about 100% code coverage, which I for instance do when I develop small modules or packages, this becomes important as it would give out more value.


In the following example, a coverage report that would tell me that case 2 is not covered directly would incite me to create a test case for it, and discover an easy bug (very contrived example here obviously)
```js

function foo(x) {
  let object = null;
  switch (x) {
	case 1:
                object = { method: () => 'ok' };
	case 2: // reported as reached
                return object.method();
  }
}

test('should return "ok"', t => {
  t.is(foo(1), 'ok');
});

// Forgot to test the case where we enter directly through `case 2`
```

I'm not sure what would be harmful if the branch coverage would change to handle this case. Except some projects that would drop from their 100% code coverage to something lower, but who I hope would be glad the tool pinpointed some holes in their tests.

**Comment by bcoe** [comment]
@jfmengels as long as there are break statements, coverage will be what you'd expect:

```js
function foo(x) {
  let object = null;
  switch (x) {
	case 1:
                object = { method: () => 'ok' };
                break;
	case 2: // reported as reached
                return object.method();
  }
}

test('should return "ok"', t => {
  t.is(foo(1), 'ok');
});
```

This will leave `case 2` uncovered; I think I agree with @ericelliott on this one, that things are behaving as expected; worth noting, although test coverage doesn't catch this bug, linting tools like [standard](https://github.com/feross/standard) will given you an indication of this potential foot gun:

` /Users/benjamincoe/bcoe/nyc/branch.js:6:2: Expected a 'break' statement before 'case'.`

**Comment by jfmengels** [comment]
> as long as there are break statements, coverage will be what you'd expect:

Absolutely agree, but only if every case has its own unique body.

```js
// Example 1
switch (x) {
  case 1: // has its own body
    // ...
    break;
  case 2:  // has its own body
    return // ...
}

// Example 2
switch (x) {
	case 1: // does not have its own body, as it's the same as case 2
	case 2:
		return 'ok';
}
```

> although test coverage doesn't catch this bug, linting tools like standard will given you an indication of this potential foot gun

ESLint/standard catch example 1, but they do not catch example 2. I actually [proposed a rule](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/72) for this in an ESLint plugin, but thought I would first try my hand at changing things at the source.

**Comment by ericelliott** [comment]
IMO, using `break` (as opposed to `return`) is the foot-gun. Example 2 is fine. If you want unique coverage for every case, use discipline.

Maybe enforcing entry coverage for every case could be an optional feature of coverage tools? (Certainly not a bug).

**Comment by bcoe** [comment]
@jfmengels if you'd like to keep this conversation open, mind opening an issue on the istanbuljs monorepo that we're consolidating work on 👍 

https://github.com/istanbuljs/istanbuljs
